
title: <p align="center"> Anandu Balachandran </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/anandu-kb/">LinkedIn</a> |
  <a href="https://github.com/Anandu07/">GitHub</a>
 
  <br>  
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
